#!/bin/bash
set -euo pipefail

config_dir=/data/coolify/applications/y6s32fammnhcr2l7x4ulkhlw

docker compose \
    --env-file .env \
    -f "$config_dir/docker-compose.yaml" \
    -f "$config_dir/docker-compose.coolify.yml" \
    up -d --no-build --pull always
